import type { EventWithCreator } from '@/types';

/** Static Phase-1 seed markers. These are used until the events query is
 *  wired up and Realtime is switched on in Phase 2. Coordinates cluster
 *  around Kraków so the initial demo camera has visible markers. */
const NOW = new Date();
const iso = (d: Date) => d.toISOString();
const dateOnly = (d: Date) => d.toISOString().slice(0, 10);

const demoCreator = {
  id: '00000000-0000-0000-0000-000000000001',
  username: 'tony',
  display_name: 'Tony',
  avatar_url: null,
};

export const DEMO_EVENTS: EventWithCreator[] = [
  {
    id: 'demo-1',
    creator_id: demoCreator.id,
    title: "Party at Tony's",
    description: 'Rooftop hangout, bring your own drinks.',
    emoji: '🎉',
    latitude: 50.0614,
    longitude: 19.9366,
    event_date: dateOnly(NOW),
    event_time: '20:00',
    max_participants: 30,
    visibility: 'public',
    created_at: iso(NOW),
    updated_at: iso(NOW),
    creator: demoCreator,
    participant_count: 12,
    is_joined: false,
  },
  {
    id: 'demo-2',
    creator_id: demoCreator.id,
    title: 'Coffee Meetup',
    description: 'Latte and lightning talks.',
    emoji: '☕',
    latitude: 50.0619,
    longitude: 19.9403,
    event_date: dateOnly(NOW),
    event_time: '09:30',
    max_participants: 8,
    visibility: 'public',
    created_at: iso(NOW),
    updated_at: iso(NOW),
    creator: demoCreator,
    participant_count: 4,
    is_joined: false,
  },
  {
    id: 'demo-3',
    creator_id: demoCreator.id,
    title: 'LAN Party',
    description: 'BYO laptop. Snacks provided.',
    emoji: '🎮',
    latitude: 50.0658,
    longitude: 19.9449,
    event_date: dateOnly(new Date(NOW.getTime() + 86_400_000)),
    event_time: '18:00',
    max_participants: 16,
    visibility: 'public',
    created_at: iso(NOW),
    updated_at: iso(NOW),
    creator: demoCreator,
    participant_count: 9,
    is_joined: false,
  },
  {
    id: 'demo-4',
    creator_id: demoCreator.id,
    title: 'Football Match',
    description: '5-a-side pickup game.',
    emoji: '⚽',
    latitude: 50.0684,
    longitude: 19.9276,
    event_date: dateOnly(new Date(NOW.getTime() + 2 * 86_400_000)),
    event_time: '17:00',
    max_participants: 10,
    visibility: 'public',
    created_at: iso(NOW),
    updated_at: iso(NOW),
    creator: demoCreator,
    participant_count: 6,
    is_joined: false,
  },
  {
    id: 'demo-5',
    creator_id: demoCreator.id,
    title: 'Study Group',
    description: 'React Native deep dive.',
    emoji: '📚',
    latitude: 50.0567,
    longitude: 19.9445,
    event_date: dateOnly(new Date(NOW.getTime() + 3 * 86_400_000)),
    event_time: '15:00',
    max_participants: 6,
    visibility: 'public',
    created_at: iso(NOW),
    updated_at: iso(NOW),
    creator: demoCreator,
    participant_count: 3,
    is_joined: false,
  },
  {
    id: 'demo-6',
    creator_id: demoCreator.id,
    title: 'Dog Walk',
    description: 'Meet by the park entrance.',
    emoji: '🐕',
    latitude: 50.0533,
    longitude: 19.9365,
    event_date: dateOnly(NOW),
    event_time: '08:00',
    max_participants: null,
    visibility: 'public',
    created_at: iso(NOW),
    updated_at: iso(NOW),
    creator: demoCreator,
    participant_count: 7,
    is_joined: false,
  },
];

export const DEMO_CENTER = { latitude: 50.0614, longitude: 19.9383 };
